config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'


    resources :comments
  resources :posts do
    collection do
      get :search
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord


  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/post.rb
class Post < ApplicationRecord
  #has_many :comments
  belongs_to :user
  has_many :comments, as: :commentable
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings do
    mappings dynamic: false do
      indexes :author, type: :text
      indexes :title, type: :text, analyzer: :english
      indexes :body, type: :text, analyzer: :english
      indexes :tags, type: :text, analyzer: :english
      indexes :published, type: :boolean
    end
  end

  def self.search_published(query)
    self.search({
                  query: {
                    bool: {
                      must: [
                        {
                          multi_match: {
                            query: query,
                            fields: [:author, :title, :body, :tags]
                          }
                        },
                        {
                          match: {
                            published: true
                          }
                        }]
                    }
                  }
                })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_commentable, only: :create

  def new
    @comment = Comment.new
  end

  def create

    Comment.create(comment_params.merge(:commentable => @commentable))

# @comment_user=comments.build(comment_params)
# @comment_user.save
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:message,:user_id)

  end

  def find_commentable


    if params.require(:comment)[:post_id]
      @commentable = Post.find_by(id: params.require(:comment)[:post_id])
    elsif params.require(:comment)[:comment_id]
      @commentable = Comment.find_by(id: params.require(:comment)[:comment_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
     @comment=Comment.new

    @comments=@post.comments


  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create

    @post = Post.create(title: params.require(:post)[:title],body: params.require(:post)[:body],author: params.require(:post)[:author],user_id: current_user.id)

    redirect_to(posts_path)

  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params

      params.fetch(:title,:body,:author)
    end

  def search
    query = params[:search_posts].presence && params[:search_posts][:query]

    if query
      @posts = Post.search_published(query)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  <p class="navbar-text float-right">
  </p>
  </body>
</html>

app/views/layouts/footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
  </div>
  <!-- /.container -->
</footer>

app/views/layouts/header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">Blog Post</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Services</a>
                </li>
                <li class="nav-item">
                  <% if user_signed_in? %>
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
                    </li>
                <li class="nav-item">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
                </li>
                    <%end %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/posts/_form.html.erb
<div class="login-form">
  <h2 class="text-center" >Create Post</h2>


<%= form_with(model: post) do |form| %>



      <div class="form-group">
        <%= form.label :author %><br />
        <%= form.text_field :author, class: "form-control",autofocus: true, autocomplete: "email" %>
      </div>
      <div class="form-group">
        <%= form.label :title %><br />
        <%= form.text_field :title, class: "form-control",autofocus: true, autocomplete: "email" %>
      </div>
      <div class="form-group">
        <%= form.label :body %><br />
        <%= form.text_area :body, class: "form-control",autofocus: true, autocomplete: "email" %>
      </div>

    <div class="actions">
    <%= form.submit "submit",class: "btn btn-primary btn-block"%>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render template: "layouts/header" %>

<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<p>
<!--  Press <%#= link_to 'here', search_posts_path %> to search for posts.-->
</p>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%# @posts.each do |post| %>
<!--    <tr>-->
<!--      <td><%#= link_to 'Show', post %></td>-->
<!--      <td><%#= link_to 'Edit', edit_post_path(post) %></td>-->
<!--      <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--    </tr>-->
  <%# end %>
  </tbody>
</table>

<br>




<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<%= link_to 'New Post', new_post_path %>
<div class="container cta-100 ">
  <div class="container">
    <div class="row blog">
      <div class="col-md-12">
        <div id="blogCarousel" class="carousel slide container-blog" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#blogCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#blogCarousel" data-slide-to="1"></li>
          </ol>
          <!-- Carousel items -->
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="row">
                <% @posts.each do |post|%>
                <div class="col-md-4" >
                  <div class="item-box-blog">
                    <div class="item-box-blog-image">
                      <!--Date-->
                      <div class="item-box-blog-date bg-blue-ui white"> <span class="mon">Augu 01</span> </div>
                      <!--Image-->
                      <figure> <img alt="" src="https://cdn.pixabay.com/photo/2017/02/08/14/25/computer-2048983_960_720.jpg"> </figure>
                    </div>
                    <div class="item-box-blog-body">
                      <!--Heading-->
                      <div class="item-box-blog-heading">
                        <a href="#" tabindex="0">
                          <h5><%= post.title %></h5>
                        </a>
                      </div>
                      <!--Data-->
                      <div class="item-box-blog-data" style="padding: px 15px;">
                        <p><i class="fa fa-user-o"></i> Admin, <i class="fa fa-comments-o"></i> Comments(3)</p>
                      </div>
                      <!--Text-->
                      <div class="item-box-blog-text">
                        <p><%= post.body %></p>
                      </div>
                      <%= link_to 'Show', post ,class: "btn bg-blue-ui white read"%>
                      <!--Read More Button-->
                    </div>
                  </div>
                </div>


                  <%end %>


              </div>
              <!--.row-->
            </div>
            <!--.item-->

            <!--.item-->
          </div>
          <!--.carousel-inner-->
        </div>
        <!--.Carousel-->
      </div>
    </div>
  </div>
</div>




<%= render template: "layouts/footer" %>

app/views/posts/new.html.erb
<%= render template: "layouts/header" %>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
<%= render template: "layouts/footer" %>

app/views/posts/search.html.erb
<<h1>Elastic search for posts</h1>

<%= form_for :search_posts, url: search_posts_path, method: :get do |form| %>
  <%= form.text_field :query, value: params[:search_posts].presence && params[:search_posts][:query] %>
  <%= form.submit 'Search' %>
<% end %>

<% unless @posts.nil? %>
  <% if @posts.empty? %>
    <h2>No posts found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>

    <table style="width: 100%;">
      <thead>
      <tr>
        <th>Author</th>
        <th>Title</th>
        <th>Tags</th>
        <th>Published on</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.author %></td>
          <td><%= post.title %></td>
          <td><%= post.tags %></td>
          <td><%= post.published_on %></td>
          <td><%= link_to 'View', post_path(post.id) %></td>
        </tr>
      <% end %>
      <tbody>
      </table>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/blog-post.css" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<%= render template: "layouts/header" %>

<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4"><%= @post.title%></h1>

      <!-- Author -->
      <p class="lead">
        by
        <a href="#">Start Bootstrap</a>
      </p>
      <hr>
      <!-- Date/Time -->
      <p>Posted on January 1, 2019 at 12:00 PM</p>
      <hr>
      <!-- Preview Image -->
      <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

      <hr>

      <!-- Post Content -->
      <p class="lead"><%=@post.body %></p>

      <hr>

      <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
      <%= form_for @comment do |form| %>
            <div class="form-group">
        <%= form.text_area :message ,class: "form-control"%>
            </div>
        <%= form.hidden_field :post_id,  value: @post.id %>
            <%= form.hidden_field :user_id,  value: current_user.id %>
            <%= form.submit "Submit" ,class: "btn btn-primary"%>
      <% end %>
        </div>
      </div>
      <!-- Comments Form -->



      <% @comments.each do |comment|%>
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            <%= comment.message %>

            <% (comment.comments).each do |coment|%>
            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                <%= coment.message %>
              </div>

            </div>
            <% end %>


              <h6 class="card-header">Leave a Comment:</h6>
              <div class="card-body">
                <%= form_for @comment do |form| %>
                  <div class="form-group">
                    <%= form.text_field :message %>
                  </div>
                  <%= form.hidden_field :comment_id,  value: comment.id %>
                  <%= form.hidden_field :user_id,  value: current_user.id %>
                  <%= form.submit "Submit" ,class: "btn btn-primary"%>
                <% end %>
              </div>



          </div>
        </div>
      <% end %>

<!--       Single Comment -->


<!--       Comment with nested comments -->
<!--      <div class="media mb-4">-->
<!--        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">-->
<!--        <div class="media-body">-->
<!--          <h5 class="mt-0">Commenter Name</h5>-->
<!--          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.-->

<!--          <div class="media mt-4">-->
<!--            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">-->
<!--            <div class="media-body">-->
<!--              <h5 class="mt-0">Commenter Name</h5>-->
<!--              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.-->
<!--            </div>-->
<!--          </div>-->

<!--          <div class="media mt-4">-->
<!--            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">-->
<!--            <div class="media-body">-->
<!--              <h5 class="mt-0">Commenter Name</h5>-->
<!--              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.-->
<!--            </div>-->
<!--          </div>-->

<!--        </div>-->
<!--      </div>-->

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
        </div>
      </div>

    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<%= render template: "layouts/footer" %>
<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>